nameOverride: argocd

installCRDs: true

controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-operator
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

server:
  extraArgs:
    - --insecure

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-operator
  podAnnotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-issuer"
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/whitelist-source-range: "0.0.0.0/0"
    hosts:
      - "argocd.demo.spic.me"
    tls:
      - secretName: argocd-server-tls
        hosts:
          - "argocd.demo.spic.me"

  config:
    url: "https://argocd.demo.spic.me"

    repositories: |
      - name: env-demo
        type: git
        url: https://github.com/opspresso/argocd-env-demo
      - name: stable
        type: helm
        url: https://kubernetes-charts.storage.googleapis.com
      - name: argo
        type: helm
        url: https://argoproj.github.io/argo-helm

    oidc.config: |
      name: SSO
      clientID: 'argo-cd'
      clientSecret: 'd91fdbbc-5dbb-43ab-b388-ce4170ff79c6'
      issuer: 'https://keycloak.demo.spic.me/auth/realms/demo'
      requestedScopes:
        - openid
        - email
        - profile
        - groups

  # https://argoproj.github.io/argo-cd/operator-manual/user-management/keycloak/

  rbacConfig:
    policy.default: role:readonly
    policy.csv: |
      g, "/admin", role:admin

  additionalApplications:
    - name: docs
      project: default
      source:
        repoURL: https://github.com/opspresso/argocd-env-demo
        targetRevision: HEAD
        path: nalbam-docs/demo-prod
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    - name: sample-node-dev
      project: default
      source:
        repoURL: https://github.com/opspresso/argocd-env-demo
        targetRevision: HEAD
        path: sample-node/demo-dev
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    - name: sample-node-prod
      project: default
      source:
        repoURL: https://github.com/opspresso/argocd-env-demo
        targetRevision: HEAD
        path: sample-node/demo-prod
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    - name: sample-spring-dev
      project: default
      source:
        repoURL: https://github.com/opspresso/argocd-env-demo
        targetRevision: HEAD
        path: sample-spring/demo-dev
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
    - name: sample-tomcat-dev
      project: default
      source:
        repoURL: https://github.com/opspresso/argocd-env-demo
        targetRevision: HEAD
        path: sample-tomcat/demo-dev
      destination:
        server: https://kubernetes.default.svc
        namespace: demo-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

  additionalProjects: []
